### ISSUE TITLE
Exceeded our limits despite only a few requests

### ISSUE THREAD

**Issue by mathiasjepsen** [PeterL93/PythonProject#2]
After trying to figure out how to even get started on the assignment, having only done <20 requests, we're getting a response code of 429.

Is there any way you can just provide a complete .csv file for us to download and use, or at least a URL to an endpoint that we can retrieve all the required data from, so we only have to do it once and then just reuse what we got. Otherwise we're essentially stuck.

**Comment by Gozzah** [comment]
Koster 479kr pr mdr  at få 1000 requests om dagen. Vi har samme problem som jer. Så den opgave bliver ikke lavet :) Nyd søndagen :)

**Comment by mvbmir** [comment]
You can get as many keys as you have mails. Also, a tip is you can find an option to get a csv file from the api, instead of json data :)

**Comment by Ejdems666** [comment]
Look here
https://github.com/PeterL93/PythonProject/issues/3
