### ISSUE TITLE
How do i download "a" file?

### ISSUE THREAD

**Issue by emil-malmgaard-rasmussen** [PeterL93/PythonProject#3]
I can't see where im suppose to download any file which should contain the information? 

When i click the link, I just see their frontpage and here i can read about the coin api or get a free product key. Do I need to sign up to get my hands on the file? 

Best regards

**Comment by mvbmir** [comment]
Hey, I just updated the README.md, it has the answer there.

**Comment by Ejdems666** [comment]
I added a csv file for the first question, will add the rest soon.
It's just BTC to USD. but no need to do more currencies

https://raw.githubusercontent.com/PeterL93/PythonProject/master/trades_march_to_april_2017.csv

**Comment by Ejdems666** [comment]
# Update

The file with transactions linked in previous comments can be used for questions 1, 2 and 5.

**Comment by Ejdems666** [comment]
# Update

I changed the data file for Qs 1, 2 and 5
here is a new link. https://raw.githubusercontent.com/PeterL93/PythonProject/master/trades_march_to_april_2018.csv

It appears, that you can only get 100 lines back no matter what,  but it's good enough.

**Comment by mvbmir** [comment]
You can actually use the limit parameter, and get up to 100000 records.

**Comment by Ejdems666** [comment]
## Update 

The file for Q 1 2 and 5 is now 10 000 lines.


It appears that it's not just the number of requests, but also the number of items of data you're requesting.
So it cuts off the API KEY way before 100 requests. that's something we did not foresee when we just briefly tested the endpoints.

**Comment by Ejdems666** [comment]
# Big Update, all is well

we changed the questions 3 and 4, so you can complete them with the current file.

So in summary, you have the csv file here: https://raw.githubusercontent.com/PeterL93/PythonProject/master/trades_march_to_april_2018.csv
All the questions are answerable, have fun :)
